import 'package:flutter/material.dart';

class Product {
  final String image, title, description;
  final int size, id;
  final double price;
  final Color color;

  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.color,
  });
}

final products = [
  Product(
    id: 1,
    title: "Plato Rosado",
    image: "assets/Images-products/image1.png",
    price: 25.50,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color(0xFF3D82AE),
  ),
  Product(
    id: 2,
    title: "Plato Anaranjado",
    image: "assets/Images-products/image2.png",
    price: 25.80,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color(0xFF13A581),
  ),
  Product(
    id: 3,
    title: "Plato Celeste",
    image: "assets/Images-products/image3.png",
    price: 25.90,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color(0xFFAEAA3D),
  ),
  Product(
    id: 4,
    title: "Hueso de Ule",
    image: "assets/Images-products/image4.png",
    price: 18.20,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color.fromARGB(255, 84, 61, 174),
  ),
  Product(
    id: 5,
    title: "Hueso de Juguete",
    image: "assets/Images-products/image5.png",
    price: 28.30,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color.fromARGB(255, 174, 82, 61),
  ),
  Product(
    id: 6,
    title: "Hueso de Juguete",
    image: "assets/Images-products/image6.png",
    price: 28.90,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color.fromARGB(255, 108, 61, 174),
  ),
  Product(
    id: 7,
    title: "Hueso",
    image: "assets/Images-products/image7.png",
    price: 15.50,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color.fromARGB(255, 159, 174, 61),
  ),
  Product(
    id: 8,
    title: "Hueso",
    image: "assets/Images-products/image8.png",
    price: 15.30,
    description: "Especialmente para Mascotas, con diseño atractivo",
    size: 12,
    color: const Color.fromARGB(255, 174, 61, 78),
  ),
  Product(
    id: 9,
    title: "Pelotas con luces",
    image: "assets/imgs/p5.png",
    price: 10.60,
    description: "para iluminar y decorar",
    size: 12,
    color: const Color(0xFF4F12C1),
  ),
  Product(
    id: 10,
    title: "Motor de agua small",
    image: "assets/imgs/p6.png",
    price: 40.90,
    description: "para transferir agua a pesceras chicas",
    size: 12,
    color: const Color(0xFFC7369D),
  ),
  Product(
    id: 11,
    title: "Motor de agua medium",
    image: "assets/imgs/p7.png",
    price: 60.90,
    description: "para transferir agua a pesceras medianas",
    size: 12,
    color: const Color(0xFF0A4297),
  ),
  Product(
    id: 12,
    title: "Kit para pescera",
    image: "assets/imgs/p8.png",
    price: 120.40,
    description: "para oxigenar, traferir agua y limpiar",
    size: 12,
    color: const Color(0xFF2C9622),
  ),
  Product(
    id: 13,
    title: "Pescera con leds",
    image: "assets/imgs/p9.png",
    price: 150.30,
    description: "pescera para la comodidad de tu pez",
    size: 12,
    color: const Color(0xFF949622),
  ),
  Product(
    id: 14,
    title: "Comida Small fish",
    image: "assets/imgs/p10.png",
    price: 25.20,
    description: "para la mejor alimentacion de tu mascota",
    size: 12,
    color: const Color(0xFF7BCF5D),
  ),
  Product(
    id: 15,
    title: "Comida Novo Dragon",
    image: "assets/imgs/p11.png",
    price: 30.90,
    description: "para la mejor alimentacion de tu mascota",
    size: 12,
    color: const Color(0xFF32C38A),
  ),
  Product(
    id: 16,
    title: "Pescera acondicionada",
    image: "assets/imgs/p12.png",
    price: 200.60,
    description: "para la mejor comodidad de tu mascota",
    size: 12,
    color: const Color(0xFF124CB2),
  ),
  Product(
    id: 17,
    title: "Mueble con pescera",
    image: "assets/imgs/p13.png",
    price: 300,
    description: "para redicir espacios",
    size: 12,
    color: const Color(0xFFB21269),
  ),
  Product(
    id: 18,
    title: "Pescera cristal templado",
    image: "assets/imgs/p15.png",
    price: 250,
    description: "para la mejor seguridad",
    size: 12,
    color: const Color(0xFF871630),
  ),
];
