// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBviPGcId_5WGEJgjf4nrECS0jtVwEzEhY',
    appId: '1:496805104117:web:67de3a06480bacc681f8bc',
    messagingSenderId: '496805104117',
    projectId: 'chems-pet-certus',
    authDomain: 'chems-pet-certus.firebaseapp.com',
    storageBucket: 'chems-pet-certus.appspot.com',
    measurementId: 'G-LS1ZBWRRT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZ_QeeVA9ROrajfdV8O7gHz7eylLEeJQ',
    appId: '1:496805104117:android:bd46ad22b8503d9681f8bc',
    messagingSenderId: '496805104117',
    projectId: 'chems-pet-certus',
    storageBucket: 'chems-pet-certus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGZk1KRoLA8-00Cbfe6h2VL2LRIP4Sts',
    appId: '1:496805104117:ios:5212094967822c9d81f8bc',
    messagingSenderId: '496805104117',
    projectId: 'chems-pet-certus',
    storageBucket: 'chems-pet-certus.appspot.com',
    androidClientId: '496805104117-751v6centgk055vup6sr9ev3qs6gp4p5.apps.googleusercontent.com',
    iosClientId: '496805104117-c42i6kgl4fqp3o1bca3l31q05i43o1r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chemsPetApp',
  );
}
